import Foundation

struct L {
    static let appTitle = "NEXUS"
    static let appSubtitle = "新しい4x5戦略ゲーム"
    static let play = "プレイ"
    static let howToPlay = "遊び方"
    static let chooseMode = "モード選択"
    static let vsAI = "AI対戦"
    static let vsAIDesc = "コンピューターと対戦"
    static let twoPlayerMode = "2人プレイ"
    static let twoPlayerDesc = "友達と一緒にプレイ"
    static let gotIt = "わかった"
    static let back = "戻る"
    static let yourTurn = "あなたのターン"
    static let youWin = "勝利"
    static let youLose = "敗北"
    static let playAgain = "もう一度"
    static let backToModeSelect = "モード選択に戻る"
    static let selectSkill = "スキル選択"
    static let energy = "エネルギー"
    static let skill = "スキル"
    static let stats = "統計"
    static let winRate = "勝率"
    static let totalPlays = "合計プレイ数"
    static let wins = "勝利数"
    static let bestScore = "最高スコア"
    static let winStreak = "連勝数"
}
