import Foundation

struct L {
    static let appTitle = String(localized: "NEXUS")
    static let appSubtitle = String(localized: "A new 4x5 strategy game")
    static let play = String(localized: "Play")
    static let howToPlay = String(localized: "How to Play")
    static let chooseMode = String(localized: "Choose Mode")
    static let vsAI = String(localized: "VS AI")
    static let vsAIDesc = String(localized: "Play against the computer")
    static let twoPlayerMode = String(localized: "2P Mode")
    static let twoPlayerDesc = String(localized: "Play with a friend")
    static let gotIt = String(localized: "Got It")
    static let back = String(localized: "Back")
    static let yourTurn = String(localized: "YOUR TURN")
    static let youWin = String(localized: "YOU WIN")
    static let youLose = String(localized: "YOU LOSE")
    static let playAgain = String(localized: "Play Again")
    static let backToModeSelect = String(localized: "Back to Mode Select")
    static let selectSkill = String(localized: "Select a Skill")
    static let energy = String(localized: "Energy")
    static let skill = String(localized: "Skill")
    static let stats = String(localized: "Stats")
    static let winRate = String(localized: "Win Rate")
    static let totalPlays = String(localized: "Total Plays")
    static let wins = String(localized: "Wins")
    static let bestScore = String(localized: "Best Score")
    static let winStreak = String(localized: "Win Streak")
}
